# DB Persistent Volume for Joplin
apiVersion: v1
kind: PersistentVolume
metadata:
  name: joplin-db-volume
  labels:
    purpose: joplin
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/kubernetes/joplin-db/
  nodeAffinity:
    # note: local store will only work
    # when node affinity mathches a single node
    # otherwise, the corresponding PVC will not 
    # match it.
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-worker0
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

